services:
  db:
    image: postgres:16-alpine
    container_name: fitness-db
    environment:
      POSTGRES_DB: fitnessdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"